FROM mcr.microsoft.com/dotnet/aspnet:7.0.5-alpine3.17
ENTRYPOINT ["ping", "www.google.com"]
#RUN addgroup -g 1000 wheel && \
#    adduser --shell /sbin/nologin --disabled-password \
#    --no-create-home --uid 1000 --ingroup wheel deployer
#USER deployer