// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketStore.Data;

#nullable disable

namespace TicketStore.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230429224707_Secret_To_Merchant")]
    partial class Secret_To_Merchant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketStore.Data.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnName("artist");

                    b.Property<int>("MerchantId")
                        .HasColumnName("merchant_id");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnName("poster_url");

                    b.Property<string>("PressRelease")
                        .IsRequired()
                        .HasColumnName("press_release");

                    b.Property<decimal>("Roubles")
                        .HasColumnName("roubles");

                    b.Property<DateTime>("Time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnName("place");

                    b.Property<string>("YandexMoneyAccount")
                        .IsRequired()
                        .HasColumnName("yandex_money_account");

                    b.Property<string>("YandexMoneySecret")
                        .IsRequired()
                        .HasColumnName("yandex_money_secret");

                    b.HasKey("Id");

                    b.ToTable("merchants");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnName("event_name");

                    b.Property<bool>("Expired")
                        .HasColumnName("expired");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnName("number");

                    b.Property<int>("PaymentId")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Roubles")
                        .HasColumnName("roubles");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PaymentId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Event", b =>
                {
                    b.HasOne("TicketStore.Data.Model.Merchant", "Merchant")
                        .WithMany("Events")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Ticket", b =>
                {
                    b.HasOne("TicketStore.Data.Model.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketStore.Data.Model.Payment", "Payment")
                        .WithMany("Tickets")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Merchant", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Payment", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
