trigger:
  branches:
    include:
    - '*' 
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - '*' 
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    mkdir -p test-results/jest
    yarn run test
  workingDirectory: $(build.sourcesDirectory)/Services/TicketStore.MobileApp
  displayName: 'npm install and build'
  env:
    JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: 'test-results/jest/junit.xml' 
    searchFolder: '$(build.sourcesDirectory)/Services/TicketStore.MobileApp' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
