trigger:
  branches:
    include:
    - '*' 
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - '*' 
  paths:
    exclude:
    - README.md

stages:
- stage: client_unit_tests
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-18.04'
    continueOnError: true
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm test
      workingDirectory: $(build.sourcesDirectory)/Services/TicketStore.Web/Client
      displayName: 'npm install and test'

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# # 
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm test
#   workingDirectory: $(build.sourcesDirectory)/Services/TicketStore.Web/Client
#   displayName: 'npm install and test'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
#     testResultsFiles: 'reports/junit.xml' 
#     searchFolder: '$(build.sourcesDirectory)/Services/TicketStore.Web/Client' # Optional
#     #mergeTestResults: false # Optional
#     #failTaskOnFailedTests: false # Optional
#     #testRunTitle: # Optional
#     #buildPlatform: # Optional
#     #buildConfiguration: # Optional
#     #publishRunAttachments: true # Optional
