FROM mcr.microsoft.com/dotnet/sdk:8.0.203-alpine3.19-amd64
RUN dotnet tool install --global dotnet-ef --version 8.0.3
ENV PATH="/root/.dotnet/tools:${PATH}"
COPY ./Services/TicketStore.Data/ /app
WORKDIR /app
ENTRYPOINT ["dotnet-ef", "database", "update", "--verbose"]
