FROM mcr.microsoft.com/dotnet/sdk:5.0.202-alpine3.13
RUN dotnet tool install --global dotnet-ef --version 5.0.5
ENV PATH="/root/.dotnet/tools:${PATH}"
COPY ./Services/TicketStore.Data/ /app
WORKDIR /app
ENTRYPOINT ["dotnet-ef", "database", "update", "--verbose"]
