version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - run: dotnet clean TicketStore.Api/TicketStore.Api.csproj
      - run: dotnet restore TicketStore.Api/TicketStore.Api.csproj
      - run: dotnet build TicketStore.Api/TicketStore.Api.csproj
      - run: dotnet clean TicketStore.Web/TicketStore.Web.csproj
      - run: dotnet restore TicketStore.Web/TicketStore.Web.csproj
      - run: dotnet build TicketStore.Web/TicketStore.Web.csproj
  # deploy:
  #   requires:
  #     - build
  #   branches:
  #     only:
  #     - master
  #   steps:
  #     - run: echo Hi!

    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      # - deploy
