version: 2.1

jobs:
  client-unit-tests:
    working_directory: ~/repo/Services/TicketStore.Web/Client
    docker:
      - image: node:12.16.3-alpine3.11
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: install libraries
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: build typescript
          command: npm run build
      - run:
          name: run tests
          command: npm test
      - store_test_results:
          path: reports
  deploy:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: define version
          command: |
            echo 'export VERSION="1.7.$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      # - run:
      #     name: install sentry-cli and verify that cli was installed successfully
      #     command: |
      #       curl -sL https://sentry.io/get-cli/ | bash
      #       sentry-cli --help
      - run:
          name: update docker-compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      # - run:
      #     name: create release in sentry and associate commits with a release
      #     command: |
      #       sentry-cli releases new -p $SENTRY_PROJECT_NAME $VERSION
      - run: bash ./Scripts/publish-to-docker-hub.sh
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       ssh root@chertopolokh.ru 'rm -rf ticket_store'
      #       ssh root@chertopolokh.ru 'git clone git@github.com:FrameBassman/ticket_store.git --branch master --single-branch'
      #       ssh root@chertopolokh.ru 'export VERSION='"'$VERSION'"'; cd ticket_store && make stop-prod start-prod && make docker-cleanup -i'
      #       ssh root@chertopolokh.ru 'docker image prune --all --force'
      # - run:
      #     name: Deploy check
      #     command: |
      #       bash ./Scripts/check-deployment.sh https://chertopolokh.ru
      # - run:
      #     name: finish sentry release
      #     command: |
      #       sentry-cli releases deploys $VERSION new -e Production

workflows:
  version: 2
  frontend-unit-tests:
    jobs:
      - client-unit-tests
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     context: credentials
      #     requires:
      #       - test-integration
