version: 2.1

jobs:
  checkout:
    steps:
      - checkout
  build-api:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - run: cd ~/TicketStore.Api
      - run: dotnet clean
      - run: dotnet restore
      - run: dotnet build
  build-web:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - run: cd ~/TicketStore.Web
      - run: dotnet clean
      - run: dotnet restore
      - run: dotnet build


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - build-api
      - build-web
      - deploy
