version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: cd ~/TicketStore.Api
      - run: dotnet clean
      - run: dotnet restore
      - run: dotnet build
      - run: cd ~/TicketStore.Web
      - run: dotnet clean
      - run: dotnet restore
      - run: dotnet build
  deploy:
    requires:
      - build
    branches:
      only:
      - master
    steps:
      - run: echo Hi!

    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy
