version: 2.1

jobs:
  build-web:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_10.x |  bash - && apt-get install -y nodejs
      - run:
          command: dotnet build
          working_directory: TicketStore.Web
  build-api:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          command: dotnet build
          working_directory: TicketStore.Api
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker --version
      - run: docker-compose --version
      - run: make --version
      - run: echo $CIRCLE_BUILD_NUM
    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-api
      - build-web
      - deploy:
          requires:
            - build-api
            - build-web
