version: 2.1

jobs:
  build-web:
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run:
          command: dotnet build
          working_directory: TicketStore.Web
  build-api:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          command: dotnet build
          working_directory: TicketStore.Api
  test-api:

    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-api
      - build-web
