version: 2.1

jobs:
  build-web:
    working_directory: ~/repo/TicketStore.Web
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout:
          path: ~/repo
      - run: curl -sL https://deb.nodesource.com/setup_10.x |  bash - && apt-get install -y nodejs
      - run:
          command: dotnet build
      - run:
          command: npm run build
          working_directory: Client
  build-api:
    working_directory: ~/repo/TicketStore.Api
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout:
          path: ~/repo
      - run:
          command: dotnet build
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: chmod +x ./Scripts/deploy.sh
      - run: ./Scripts/deploy.sh
    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-api
      - build-web
      - deploy:
          filters:
            branches:
              only:
                - master
          context: docker_hub_creds
          requires:
            - build-api
            - build-web
