version: 2.1

jobs:
  build-web:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_10.x |  bash - && apt-get install -y nodejs
      - run:
          command: dotnet build
          working_directory: TicketStore.Web
      - run:
          command: npm run build
          working_directory: TicketStore.Web/Client
  build-api:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          command: dotnet build
          working_directory: TicketStore.Api
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: chmod +x ./Scripts/deploy.sh
      - run: ./Scripts/deploy.sh
    
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-api
      - build-web
      - deploy:
          branches:
            only:
              - master
          context: docker_hub_creds
          requires:
            - build-api
            - build-web
