version: '3.6'

services:
    store_farewell:
        build:
            context: .
            dockerfile: ./Services/Farewell/Dockerfile.Production
            args:
                - NODE_ENV=production
        ports:
            - 4000:80
        labels:
            - "traefik.port=80"
    store_proxy:
        build:
            context: .
            dockerfile: ./Services/Proxy/Dockerfile.Test
