services:
    postgres:
        build:
            context: .
            dockerfile: ./Services/Postgres/Dockerfile
        container_name: postgres
        volumes:
            - pgsdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    pgsdata: