version: '3.6'

services:
    store_api:
        image: "docker.io/framebassman/store-api:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/TicketStore.Api/Dockerfile.Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - SENTRY_RELEASE=${VERSION}
    store_web:
        image: "docker.io/framebassman/store-web:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/TicketStore.Web/Dockerfile.Production
            args:
                - REACT_APP_ENVIRONMENT=Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - SENTRY_RELEASE=${VERSION}
    store_proxy:
        image: "docker.io/framebassman/store-proxy:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/Proxy/Dockerfile.Production
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./Services/Proxy/certs/acme.json:/acme.json
