version: '3'

services:
    store_api:
        image: "docker.io/framebassman/store-api:1.2.${CIRCLE_BUILD_NUM}"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    store_web:
        image: "docker.io/framebassman/store-web:1.2.${CIRCLE_BUILD_NUM}"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
