version: '3.6'

services:
    store_farewell:
        container_name: store_farewell
        labels:
            - "traefik.enable=true"
            - "traefik.backend=store_farewell"
            - "traefik.frontend.rule=PathPrefixStrip:/;ReplacePathRegex: ^/index(.html)? /"
            - "traefik.docker.network=ticket_store_default"
    store_proxy:
        container_name: store_proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
