version: '3.6'

services:
    store_api:
        build:
            context: .
            dockerfile: ./TicketStore.Api/Dockerfile.Development
        depends_on:
            - postgres
            - fake_sender
        ports:
            - 3000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Test
    store_web:
        ports:
            - 4000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Test
    postgres:
        build:
            context: .
            dockerfile: ./Postgres/Dockerfile
        container_name: postgres
        volumes:
            - pgsdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=store
            - POSTGRES_USER=store
            - POSTGRES_PASSWORD=W6TTT3WY4Nzqpj5z
        logging:
            driver: none
    fake_sender:
        image: framebassman/fake-sender:1.2.0
        container_name: fake_sender
        ports:
            - 5000:5050
        volumes:
            - /var/log/fake_sender:/var/log

volumes:
    pgsdata: