version: '3.6'

services:
    store_api:
        build:
            context: .
            dockerfile: ./TicketStore.Api/Dockerfile
    store_web:
        build:
            context: .
            dockerfile: ./TicketStore.Web/Dockerfile
