version: '3.6'

services:
    store_farewell:
        build:
            context: .
            dockerfile: ./Services/Farewell/Dockerfile.Development
        ports:
            - 4000:3000
        labels:
            - "traefik.port=3000"
        environment:
            - REACT_APP_ENVIRONMENT=Development
    store_proxy:
        build:
            context: .
            dockerfile: ./Services/Proxy/Dockerfile.Development
        logging:
            driver: none
