version: '3.6'

services:
    store_farewell:
        image: "docker.io/framebassman/store-farewell:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/Farewell/Dockerfile.Production
            args:
                - NODE_ENV=production
        ports:
            - 4000:80
        labels:
            - "traefik.port=80"
    store_proxy:
        image: "docker.io/framebassman/store-proxy:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/Proxy/Dockerfile.Production
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./Services/Proxy/certs/acme.json:/acme.json
