version: '3.6'

services:
    store_api:
        image: "docker.io/framebassman/store-api:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/TicketStore.Api/Dockerfile.Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - SENTRY_RELEASE=${VERSION}
    store_web:
        image: "docker.io/framebassman/store-web:${VERSION}"
        build:
            context: .
            dockerfile: ./Services/TicketStore.Web/Dockerfile.Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - SENTRY_RELEASE=${VERSION}
    store_proxy:
        image: "docker.io/framebassman/store-proxy:${VERSION}"
