version: '3.6'

services:
    store_api:
        container_name: store_api
        build:
            context: .
            dockerfile: ./TicketStore.Api/Dockerfile.Development
        depends_on:
            - postgres
        ports:
            - 3000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        tty: true
    store_web:
        container_name: store_web
        ports:
            - 4000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    postgres:
        build:
            context: .
            dockerfile: ./Postgres/Dockerfile
        container_name: postgres
        volumes:
            - pgsdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=store
            - POSTGRES_USER=store
            - POSTGRES_PASSWORD=W6TTT3WY4Nzqpj5z
        logging:
            driver: none

volumes:
    pgsdata: