version: '3.6'

services:
    store_api:
        image: "docker.io/framebassman/store-api:1.2.${CIRCLE_BUILD_NUM}"
        build:
            context: .
            dockerfile: ./TicketStore.Api/Dockerfile.Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    store_web:
        image: "docker.io/framebassman/store-web:1.2.${CIRCLE_BUILD_NUM}"
        build:
            context: .
            dockerfile: ./TicketStore.Web/Dockerfile.Production
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    store_proxy:
        image: "docker.io/framebassman/store-proxy:1.2.${CIRCLE_BUILD_NUM}"
