FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-alpine3.11 AS build-env

RUN apk add --update 'nodejs=12.15.0-r1' 'npm=12.15.0-r1'

COPY ./Services/TicketStore.Web/ /app
COPY ./Services/TicketStore.Data/ /TicketStore.Data
WORKDIR /app
RUN dotnet restore
RUN dotnet build
ENTRYPOINT dotnet watch run
