debug = false
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

# API definition
[api]
  debug = false
  dashboard = false

# Enable retry sending request if network error
[retry]
# Number of attempts
#
# Optional
# Default: (number servers in backend) -1
#
attempts = 3

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "demo2.chertopolokh.ru"
watch = true
exposedByDefault = false
swarmMode = false
