log:
  level: INFO
  filePath: "/logs/traefik.log"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

entryPoints:
  http-point:
    address: :80
