// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketStore.Data;

namespace TicketStore.Data.Migrations.store_db
{
    [DbContext(typeof(store_dbContext))]
    [Migration("20190702155435_TicketAndPayment")]
    partial class TicketAndPayment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TicketStore.Data.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<bool>("Expired")
                        .HasColumnName("expired");

                    b.Property<string>("Number")
                        .HasColumnName("number");

                    b.Property<int>("PaymentId")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Roubles")
                        .HasColumnName("roubles");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("TicketStore.Data.Model.Ticket", b =>
                {
                    b.HasOne("TicketStore.Data.Model.Payment", "Payment")
                        .WithMany("Tickets")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
