language: node_js
node_js:
- '12.13.0'

cache:
  directories:
    - "node_modules"

script:
  # - yarn test
  - yarn build
  - echo chertopolokh.ru > public/CNAME

deploy:
  provider: pages
  token: $GITHUB_AUTH_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: public
  repo: kolenkainc/chertopolokh_build
  target_branch: master
  on:
    branch: master
